_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: d1795abf-11b4-49db-bb07-6a013c34b306
name: 'Employee Management Portal'
mail: test.site.007@innoraft.com
slogan: ''
page:
  403: /node/14
  404: /node/13
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
